[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
shared.workspace = true
iced = "0.13.1"
serde_json = "1.0.140"
