[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
shared.workspace = true
iced = { git = "https://github.com/iced-rs/iced.git", branch = "master" }
serde_json = "1.0.140"
reqwest = "0.12.20"
