services:
  app:
    image: rust:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}"
      OLD_DATABASE_URL: "mysql://root:sunminimart@192.168.1.13:3306/sunminimart"
    command: /workdir/server
    volumes:
      - ./target/debug/server:/workdir/server
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
